# Generated by Django 2.2 on 2022-05-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220508_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackin',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
