# Generated by Django 2.2 on 2022-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20220511_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackin',
            name='Delivered',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackin',
            name='Name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
