# Generated by Django 2.2 on 2022-05-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220527_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackin',
            name='Delivery_Date',
            field=models.DateField(),
        ),
    ]
