# Generated by Django 2.2 on 2022-05-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20220527_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackin',
            name='Delivery_Date',
            field=models.DateTimeField(),
        ),
    ]
