# Generated by Django 2.2 on 2022-05-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220527_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackin',
            name='Delivery_Date',
            field=models.DateTimeField(blank=True),
        ),
    ]
