# Generated by Django 2.2 on 2022-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20220527_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackin',
            name='Current_Location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Delivered',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Delivery_Date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Delivery_State',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Tracking_ID',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
