# Generated by Django 2.2 on 2022-05-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20220527_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackin',
            name='Delivery_State',
        ),
        migrations.AddField(
            model_name='trackin',
            name='Delivery_Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='trackin',
            name='Delivery_Country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Delivered',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trackin',
            name='Name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
